[project]
name = "qutefuzz"
version = "1.0.0"
description = "Fuzzing framework for quantum compilers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytket",
    "qiskit",
    "pytket-qiskit",
    "conan",
    "pytket @ git+https://github.com/CQCL/tket.git@main#subdirectory=pytket",
    "matplotlib",
    "sympy",
    "z3-solver",
    "cirq",
    "tket2",
    "pytket-qir",
    "qnexus",
    "tket",
    "selene-sim",
    "jinja2",
    "guppylang",
    "coverage",
    "hugr-qir @ git+https://github.com/CQCL/hugr-qir.git",
    "pyyaml>=6.0.3",
]

[tool.uv]
sources.qir-runner = { path = "libs/qir-runner/pip", editable = true }

[dependency-groups]
dev = [
    "pyright>=1.1.408",
    "ruff>=0.14.13",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]  # Enable Pyflakes, pycodestyle, Isort, and Warnings
ignore = []

[tool.pyright]
include = ["scripts", "diff_testing", "main.py"]
pythonVersion = "3.12"
typeCheckingMode = "basic"  # Ch

[tool.setuptools]
packages = ["diff_testing"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
