language: qiskit
models:
  - deepseek/deepseek-chat
  - deepseek/deepseek-reasoner
  - anthropic/claude-sonnet-4-5
  - openai/gpt-5-mini
  - gemini/gemini-3-flash-preview
n_programs: 20
n_fixing_cycles: 2
max_workers: 10
n_assemble: 100
n_circuits_per_assembly: 2
verbose: true
